export const INPUT_TEXT = "INPUT_TEXT";
export const COMMENT_CREATE = "COMMENT_CREATE";
export const SHOPING_CARD_ADD = "SHOPING_CARD_ADD";
export const SHOPING_CARD_DELETE = "SHOPING_CARD_DELETE";
export const PURCHASES_DELETE = "PURCHASES_DELETE";
export const SET_DATA = "SET_DATA";
export const CHENGE_MONEY = "CHENGE_MONEY";
